apiVersion: v1
kind: Pod
metadata:
  name: shorturl-go
spec:
  containers:
    - name: redis
      image: redis:8.4-alpine
      volumeMounts:
        - name: redis-storage
          mountPath: /data

    - name: web-server
      image: web-server:latest
      env:
        - name: REDIS_ADDR
          value: "localhost:6379"
        - name: PORT
          value: 8080

    - name: nginx
      image: nginx:1.29-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx

  volumes:
    - name: redis-storage
      persistentVolumeClaim:
        claimName: redis-data
    - name: nginx-config-vol
      configMap:
        name: nginx-config
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: nginx-logs
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        
        # 同時輸出到檔案（在 Volume 裡）以及 stdout (方便 podman logs 查看)
        access_log  /var/log/nginx/access.log  main;
        access_log  /dev/stdout  main;
        error_log   /var/log/nginx/error.log  notice;
        error_log   /dev/stderr  notice;

        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                proxy_pass http://localhost:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
