apiVersion: v1
kind: Pod
metadata:
  name: shorturl-go
spec:
  containers:

    # redis container
    - name: redis
      image: docker.io/library/redis:8.4-alpine
      volumeMounts:
        - name: redis-data
          mountPath: /data

    # web-server container
    - name: web-server
      image: web-server:latest
      env:
        - name: REDIS_ADDR
          value: "localhost:6379"
        - name: PORT
          value: 8080
        - name: USER
          valueFrom:
            secretKeyRef:
              name: USER
              key: USER
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: PASSWORD
              key: PASSWORD

    # nginx container
    - name: nginx
      image: docker.io/library/nginx:1.29-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx

  volumes:

    # redis volume
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-data

    # nginx volume
    - name: nginx-logs
      persistentVolumeClaim:
        claimName: nginx-logs

    # nginx config volume
    - name: nginx-config-vol
      configMap:
        name: nginx-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log  /var/log/nginx/access.log  main;
        access_log  /dev/stdout  main;
        error_log   /var/log/nginx/error.log  notice;
        error_log   /dev/stderr  notice;

        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                proxy_pass http://localhost:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
---